coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "diff, files"
  require_changes: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "lib/generated/"
  - "lib/utils/errors.dart"
  - "lib/utils/share.dart"
