include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/intl/**
    - lib/generated/l10n.dart
  errors:
    avoid_print: ignore
    file_names: ignore
    avoid_positional_boolean_parameters: ignore

  enable-experiment:
    - extension-methods
