name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  live_route:
    path: dependencies/live_route/
  theming:
    path: ../utils/theming
  utils:
    path: ../utils/utils
  vibration:
    path: ../vibration
  android_intent: ^2.0.0-nullsafety.2
  animations: ^2.0.0-nullsafety.0
  async: ^2.4.2
  cached_network_image: ^2.3.2+1
  collection: ^1.14.13
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  expandable: ^4.1.4
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0
  flare_flutter: ^2.0.6
  fluentui_system_icons: ^1.1.90
  flutter_hooks: ^0.16.0-nullsafety.0
  flutter_riverpod: ^0.12.0
  flutter_slidable: ^0.5.7
  flutter_typeahead: ^2.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  freezed_annotation: ^0.12.0
  google_fonts: ^1.0.0
  intl: ^0.17.0-nullsafety.2
  introduction_screen: ^1.0.9
  json_annotation: ^3.0.0
  location: ^4.0.0-nullsafety.0
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  octo_image: ^0.3.0
  overflow_view: ^0.2.2
  pedantic: ^1.9.2
  quick_actions: ^0.4.0+8
  share: ^2.0.0-nullsafety.2
  shared_preferences: ^0.5.6+3
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.0-nullsafety.1
  url_strategy: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  flex_color_scheme: ^1.3.0
  flutter_launcher_icons: ^0.8.0
  freezed: ^0.12.3
  integration_test: ^1.0.1
  json_serializable: ^3.0.0
  lint: ^1.1.1
  mockito: ^5.0.0-nullsafety.1

flutter:
  uses-material-design: true

  assets:
    - assets/profiles/
    - assets/anims/
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo/swift-white.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/swift.png"

flutter_intl:
  enabled: true
  use_deferred_loading: true
