name: swift_travel
description: A new Flutter project.
publish_to: none

version: 1.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  utils:
    path: ../utils/utils
  vibration:
    path: ../vibration
  android_intent: ^0.3.7+3
  animations: ^1.1.2
  async: ^2.4.2
  cached_network_image: ^2.3.2+1
  connectivity: ^2.0.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  expandable: ^4.1.4
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.0
  flare_flutter: ^2.0.6
  flutter_riverpod: ^0.12.0
  flutter_typeahead: ^1.8.0
  font_awesome_flutter: ^8.7.0
  freezed_annotation: ^0.12.0
  geolocator: ^6.0.0+4
  google_fonts: ^1.0.0
  intl: ^0.17.0-nullsafety.2
  introduction_screen: ^1.0.9
  json_annotation: ^3.0.1
  quick_actions: ^0.4.0+8
  share: ^0.6.5+2
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.5.3
  models:
    path: dependencies/models/
  live_route:
    path: dependencies/live_route/

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.0
  freezed: ^0.12.3
  json_serializable: ^3.4.1
  lint: ^1.1.1
  mockito: ^4.1.3
  test: ^1.15.4

flutter:
  uses-material-design: true
  # generate: true # Add this line

  assets:
    - assets/profiles/
    - assets/anims/
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter_intl:
  enabled: true
  class_name: Strings
