on:
  pull_request_target:
    types: [opened]
    branches:
      - main
    paths:
      - ".github/**"

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issue
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "protected files changed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :warning: This issue modifies the `.github/` folder. :warning:
