include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
  errors:
    included_file_warning: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: false

    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true

    # prefer_final_parameters: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
