include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/intl/**
    - lib/generated/l10n.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    sort_pub_dependencies: ignore

linter:
  rules:
    - prefer_single_quotes
  # enable-experiment:
  #   - non-nullable
