name: pr on main

on:
  pull_request_target:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ github.token }}"
