name: Flutter Build

on:
  push:
    branches:
      - master

env:
  flutter_channel: dev
  java_version: 12.x
  node_version: 12.x
  build_android: true
  flutter_build_args: ""

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Deploy Android to PlayStore Alpha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get git infos
        id: git-data
        run: |
          echo "::set-output name=hash::$(git rev-parse --short "$GITHUB_SHA")"
          echo "::set-output name=msg::$(git log -1 --pretty=format:"%s")"
          echo "::set-output name=nbr::$(git rev-list --count HEAD)"
          echo "git rev-list HEAD"
      - name: Clone dependencies
        run: git clone https://Blaxou:${{ secrets.ACCESS_TOKEN }}@github.com/Blaxou/utils.git
        working-directory: ../
      - name: Setup Java
        if: env.build_android == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Get latest Flutter release
        id: release_json
        run: echo "::set-output name=json::$(curl -s "https://storage.googleapis.com/flutter_infra/releases/releases_linux.json" | jq -r ".current_release.${{ env.flutter_channel }}")"
      - name: Get Flutter from cache
        uses: actions/cache@v2
        with:
          path: |
            /opt/hostedtoolcache/flutter
            $HOME/.pub-cache
          key: ${{ runner.OS }}-flutter-cache-${{ steps.release_json.outputs.json }}
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Setup Flutter
        run: |
          flutter packages get
      - name: Pre-build configuration
        env:
          TZ: Europe/Zurich
          COMMIT_COUNT: ${{ steps.git-data.outputs.nbr }}
        run: chmod +x CI/prebuild-github.sh && ./CI/prebuild-github.sh
      - name: Build
        run: flutter build apk --build-number ${{ steps.git-data.outputs.nbr }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ci-build-${{ steps.git-data.outputs.nbr }}
          release_name: |
            CI Build #${{ steps.git-data.outputs.nbr }}
          body: |
            *This is an automated CI build for ${{ steps.git-data.outputs.hash }}.*

            `${{ steps.git-data.outputs.msg }}`
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: travel-free-${{ steps.git-data.outputs.nbr }}.apk
          asset_content_type: application/vnd.android.package-archive

  deploy-testflight:
    timeout-minutes: 30
    name: Deploy to Testflight
    runs-on: macos-latest
    if: startsWith(github.event.head_commit.message, '$')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone dependencies
        run: git clone https://Blaxou:${{ secrets.ACCESS_TOKEN }}@github.com/Blaxou/utils.git
        working-directory: ../
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: chmod +x CI/decrypt_secrets.sh && bash CI/decrypt_secrets.sh
      - name: Get latest Flutter release
        id: release_json
        run: echo "::set-output name=json::$(curl -s "https://storage.googleapis.com/flutter_infra/releases/releases_macos.json" | jq -r ".current_release.${{ env.flutter_channel }}")"
      - name: Get Flutter from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/hostedtoolcache/flutter/
            ~/.pub-cache
            ~/Library/Caches/CocoaPods
          key: ${{ runner.OS }}-flutter-cache-${{ steps.release_json.outputs.json }}
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
      - name: Echo flutter path
        run: |
          echo $HOME
      - name: Setup Flutter
        run: |
          flutter packages get
      - name: Pre-build configuration
        env:
          TZ: Europe/Zurich
        run: chmod +x CI/prebuild.sh && ./CI/prebuild.sh
      - name: Build
        run: flutter build ios --build-number $GITHUB_RUN_NUMBER
      - name: Get hash
        id: git-data
        run: |
          echo "::set-output name=hash::$(git rev-parse --short "$GITHUB_SHA")"
          echo "::set-output name=msg::$(git log -1 --pretty=format:"%s")"
          echo "::set-output name=nbr::$GITHUB_RUN_NUMBER"
      - name: Exporting .ipa
        run: chmod +x CI/export_ipa.sh && ./CI/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: chmod +x CI/publish_testflight.sh && ./CI/publish_testflight.sh
